CREATE TABLE public.blacklisted_tokens (
    id bigint generated by default as identity,
    expires_at timestamp(6) not null,
    jti varchar(255) not null,
    primary key (id)
);

CREATE TABLE public.users (
    id uuid not null,
    created_at timestamp(6),
    email varchar(255) not null,
    google_id varchar(255),
    name varchar(255),
    password_hash varchar(255),
    primary key (id)
);

ALTER TABLE IF EXISTS public.blacklisted_tokens ADD CONSTRAINT UKq5qku39sempfq8krvx5om6orj UNIQUE (jti);
ALTER TABLE IF EXISTS public.users ADD CONSTRAINT UK6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);
ALTER TABLE IF EXISTS public.users ADD CONSTRAINT UKovh8xmu9ac27t18m56gri58i1 UNIQUE (google_id);
